### ISSUE TITLE
NuKeeper only detects 1 project when 3 are present

### ISSUE THREAD

**Issue by pavelbraginskiy** [NuKeeperDotNet/NuKeeper#299]
![image](https://user-images.githubusercontent.com/29113974/41793083-e2a4ac48-760f-11e8-852f-e1796877ad08.png)
As you can see, there is a csproj, fsproj, and vbproj present in the directory but NuKeeper only reports "Found 15 packages in use, 15 distinct, in 1 projects."

**Comment by AnthonySteele** [comment]
Thanks for the feedback.

Firstly, we didn't support `fsproj` files at all. But since they are apparently the same inside as `csproj` and `vbproj`, this is an easy fix and wil go in very soon:  #300 Win!

Secondly, is this a test case or a real project structure? Are the `csproj` and `vbproj` using the old VS2015 format or the new vs2017 format? If they're old format, are they both using the same `packages.config` file? If it's a test case, I would put each project file in a subfolder with its own `packages.config` file

**Comment by pavelbraginskiy** [comment]
This is an project structure I'm using.

Admittedly, it's a bit of an unusual case, since it's not a "real" project, and is actually a part of a code-generating tool, which unfortunately relies on everything being in one directory.

I believe this is VS2017 format, but I created them with MonoDevelop so I'm not quite sure.

**Comment by AnthonySteele** [comment]
A VS2017 format project won't need `packages.config` at all.  You can tell like this: in the new style, the `.csproj` will contain `<PackageReference>` elements for nuget packages, and in the old style it will contain `<Reference Include="`

**Comment by pavelbraginskiy** [comment]
Ah. Checked, it's 2015 format.

**Comment by AnthonySteele** [comment]
Effectively, you have one list of packages, in the `packages.config` file.

**Comment by pavelbraginskiy** [comment]
So if I remove the `<HintPath>` from the project files' `<Reference Include`s, which don't get updated, it would still build correctly getting all the information from `packages.config`?

**Comment by AnthonySteele** [comment]
I would not do that. The old format needs both parts to be there, and match each other.
This is a big advantage of the new format, it's in one place and so can't get out of sync like that.

**Comment by pavelbraginskiy** [comment]
Alright. I'll try to convert them to the new format.
