### ISSUE TITLE
Add support for VSTS

### ISSUE THREAD

**Issue by OneCyrus** [NuKeeperDotNet/NuKeeper#336]
It would be great to have VSTS support. This should be pretty similar to implement like GitHub. 

There's a GitHttpClient to do this: 
https://msdn.microsoft.com/library/microsoft.teamfoundation.sourcecontrol.webapi.githttpclient.aspx

it's published as a nuget package: 
https://www.nuget.org/packages/Microsoft.TeamFoundationServer.Client/16.136.1-preview

**Comment by AnthonySteele** [comment]
Related to #327

As either of these means making the remote source control system "plugable"

**Comment by JBoothUA** [comment]
this would be wonderful!

**Comment by phatcher** [comment]
@AnthonySteele I'm going to have a go at this as it would be useful for a couple of my projects

**Comment by AnthonySteele** [comment]
My thinking is that it could proceed along these lines:

- pull the github driver code out in `OctokitClient ` into a separate project that references `Octokit`. leave the `IGitHub` interface that it implements where it is
- Where it returns github types, e.g. `Account` we will need wrapper types that have the few fields that we need.
- rename the `IGitHub` interface something more neutral.
- provide a second implementation of this interface, in a project that references the VSTS driver.

**Comment by phatcher** [comment]
That's the sort of thing I was thinking of.  

VSTS has a REST API and an [associated client](https://www.nuget.org/packages/Microsoft.VisualStudio.Services.Client/), though when I tried to install it, the .NET Standard dependencies seem a bit borked, so I might just do a "pure" REST client using HttpClient - was trying to avoid this due to authentication etc.

So we put new wrapper interfaces/classes in NuKeeper and then proxy them for each provider type

**Comment by AnthonySteele** [comment]
great. The only thing that i would add is, if we know where we're going, small incremental PRs work best. There will be other dev work ongoing during this.

**Comment by phatcher** [comment]
I'll work independently initially i.e. get a working VSTS client before I attempt to do the change that affects any of the existing code.

That way I'll know exactly what needs to be proxied and whether there is an impedance mis-match between the models in NuKeeper, GitHub and VSTS

**Comment by MrGlenThomas** [comment]
@phatcher how's it coming along? I work with VSTS and git and have written a tool for creating and managing git branches so have some code for that.

**Comment by shep1987** [comment]
Really is a proof of concept but if anyone else it looking at this, this may help:

https://gist.github.com/shep1987/2647d0b6e1264c2f102c79d65edfa2db

Will hopefully update it with the git lines un-commented (and working) soon @MrGlenThomas have you got the branch work shared anywhere?

**Comment by shep1987** [comment]
Updated gist with a working end to end example:
Having to use PAT for API and Alt credentials to work with git, any one have ideas on how improve this? 

Microsoft.Alm.Authentication isn't NetStandard compatible yet..

**Comment by JBoothUA** [comment]
I was surprised to come across this blog:
http://tattoocoder.com/using-azuredevops-pipelines-and-nukeeper-to-automate-nuget-package-updates/

**Comment by pascalberger** [comment]
@JBoothUA The blog post shows how to use NuKeeper with Azure Pipelines and source code hosted on GitHub. This issue is about supporting repository hosted in Azure DevOps

**Comment by pascalberger** [comment]
@shep1987 Couldn't you just use the .NET client libraries which seem to target .NET standard in the latest preview version:

* [Microsoft.TeamFoundationServer.Client](https://www.fuget.org/packages/Microsoft.TeamFoundationServer.Client)
* [Microsoft.VisualStudio.Services.InteractiveClient](https://www.fuget.org/packages/Microsoft.VisualStudio.Services.InteractiveClient/)

This would give support  for all possible authentication methods and also support TFS beside Azure DevOps.

**Comment by shep1987** [comment]
Unfortunately that would break xplat, issue tracking that can be found here:

https://github.com/Microsoft/vsts-dotnet-samples/issues/93

**Comment by phatcher** [comment]
@pascalberger That's the approach I'm taking but trying to generalise the current api so that we have a common interface, this then allows us to introduce a Nukeeper.AzureDevOps assembly that has the specifics.

I've had other work priorities but I will be able to devote more time over the next couple of weeks to getting a first cut solution.

However, the most appropriate solution to authentication is to use PAT tokens so that this then allows us to have a DevOps task that can be driven with values from the pipeline - it also will locally cache the credentials so you don't get prompted every time you run the command.

I may need to step down to the REST API as the client libraries are NET Framework and yes you can run against .NET Core but you do lose portability as executing against Linux would not be possible with such a dependency

**Comment by MarcBruins** [comment]
This is finished in #513. There should be a release soon, you will be able to make a PR to your ADO(AzureDevops) enviroment.

**Comment by JBoothUA** [comment]
Amazing!!  Cannot wait to give it a try!

**Comment by shep1987** [comment]
Hey @JBoothUA,

The parameters should be almost identical to the GitHub version, for the first release there are some restrictions though:
- Repo URL will have to be the new format url `https://dev.azure.com/{org}/{project}/_git/{repo}/`
- Labels are not yet implemented
- Only  `SingleRepositoryOnly` is allowed for Fork param (set by default)

Yes the PAT goes where the GitHub token would in the console or by setting the `NuKeeper_azure_devops_token` env var

So wrapping that all up the simplest command you can run is:

`nukeeper repo https://dev.azure.com/{org}/{project}/_git/{repo}/ PAT`

or if you want to have the PAT as a env var

```
SET NuKeeper_azure_devops_token=PAT
nukeeper repo https://dev.azure.com/{org}/{project}/_git/{repo}/
```

I will work with @AnthonySteele to get the docs updated and make sure we don't break anything for the existing user base.

**Comment by phatcher** [comment]
@AnthonySteele Mine approach was taking a slightly different tack e.g. I was using project as a proxy for organisation as the PAT token typically grants access to a project and I was using the idea of {repo}.{user} for the forking approach.

Most of the ideas will transfer into the current approach.

I also have set up a nukeeper DevOps organisation so I could do real integration testing.

**Comment by JBoothUA** [comment]
I pulled down latest master (so I think I'm running what I should be?) and I'm still having problems with the repo command...

I think it might have to do with my URL?  It looks like "dev.azure.com" is expected but our url is:
"https://{org}.visualstudio.com/{project}/_git/{repo}"   could that be the problem..   

I'm currently getting:  

Unhandled Exception: Octokit.AuthorizationException: Bad credentials
   at Octokit.Connection.HandleErrors(IResponse response) in C:\projects\octokit-net\Octokit\Http\Connection.cs:line 665   when I try the repo command

**Comment by MarcBruins** [comment]
I think you are on VSTS or TFS? While we support AzureDevOps, you should probably update to AzureDevops. There is an explicite check on the uri at: https://github.com/NuKeeperDotNet/NuKeeper/blob/master/NuKeeper.AzureDevOps/AzureDevOpsSettingsReader.cs#L15 which is why it's not working for you

**Comment by JBoothUA** [comment]
it is VSTS (which was just recently rebranded to Azure DevOps)

**Comment by jabberwik** [comment]
@JBoothUA Both URLs are equivalent and both are for Azure DevOps. You should be able to use the "dev.azure.com" format.

**Comment by JBoothUA** [comment]
ok thanks, let me try to switch up the format!!  thanks @jabberwik

**Comment by MarcBruins** [comment]
Ah yes exactly as @jabberwik is saying just use the AzureDevops format and it will work

**Comment by JBoothUA** [comment]
i tried the new format and played around with a couple of things but always get the same error...

it sounds like
1) somehow there is still a problem with my PAT
2) I need some other credentials as well

I also noticed it wants the PAT as a param even though I have it set as a environment variable which seems odd.

Going to debug further, but any ideas on what to try would be appreciated as always.

Thanks everyone!!!

**Comment by jabberwik** [comment]
If you're getting exceptions from Octokit, that means it's still trying to talk to Github. Calls to ADO don't use Octokit. Are you sure you have the correct code version and URL format?

**Comment by jabberwik** [comment]
Also note that if you are running from the latest code, you can't run it with `dotnet tool` because the new release hasn't been cut yet. At the moment you'll have to do something like `dotnet run -p NuKeeper\NuKeeper.csproj -- repo [etc]`

**Comment by JBoothUA** [comment]
I was thinking the same thing about ADO not using octokit, but wasn't sure...
I pulled the latest master and just have been debugging through visual studio and running the .exe but let me play with the dotnet run -p commands.
Thanks!!

**Comment by JBoothUA** [comment]
I think that got it!!!, User Error, the dotnet run -p definitely helped!!!  I guess I was running my older installed version still.

It got all the way through the routine and I ran into a different error, not _really_ related to this thread,  but I keep having problems **RESTORING** the packages from our private ADO feeds..  I try using the --source param, but I may be using it incorrectly, because it doesn't seem to have any effect..

or maybe I need to setup my username and/or email environment variables like it looks like you have to do for git??  something like that.

I think if I can get passed this last error I can provide some screenshots or recipes, etc.
And that will be a beautiful day for me.

Backstory: At the beginning of an 'update' i see a ton of "unable to load the index for source" for our private ADO packages, but then it continues to work.!! woohoo!

However, now that I'm passed my user error, Thanks Again @jabberwik , my 'repo' command does appear to work!!!!  so I feel like this latest master is a success!!!

Unfortunately now, I think to my pre-existing error, it is getting all the way to the bottom of the 'repo' command and it does successfully restore on my .sln file.

Then it tries to run the restore on my packages.config and it _seems_ to be that same issue with my ADO private feeds.  

So I guess as it appears I _could_ hopefully create PRs now, if I could RESTORE from my ADO feeds?

I probably have a credentials issue, as this is the error I get after all is said and done:

Attempting to gather dependency information for multiple packages with respect to project ''.NETFramework,Version=v4.7.1'
Please provide credentials for: https://{}.visualstudio.com/_packaging/{}/nuget/v3/index.json
UserName:

**Comment by MarcBruins** [comment]
I think this can be closed?

**Comment by JBoothUA** [comment]
![nukeeper](https://user-images.githubusercontent.com/6255224/48670337-c645ca00-eadb-11e8-8e4f-e62817d55ae6.png)
