### ISSUE TITLE
Does NuKeeper update transitive dependencies?

### ISSUE THREAD

**Issue by LordMike** [NuKeeperDotNet/NuKeeper#407]
I wasn't able to identify this in the docs, issue tracker or by running the tool. 

In the case explained in the docs (library including newtonsoft), would NuKeeper update newtonsoft (add an explicit reference to newtonsoft in the project)?

**Comment by AnthonySteele** [comment]
NuKeeper will not add references, just update existing references.
Currently it does not recognise transitive references either.

**Comment by LordMike** [comment]
Ah thanks - too bad :)

**Comment by skolima** [comment]
Adding explicit references instead of implicit ones makes the project files grow quite a bit and also goes somewhat against what the move to the new dotnet project type was about (simplification, and automating the dependency resolution). While there's good cases for using them sometimes (mainly - security updates and bugfixes), there's currently AFAIK no available data source to actually get information about those in the .NET ecosystem, so...

We'd be definitely interested in having something akin GitHub or Greenkeeper vulnerability checker - but there's no data source for it right now.

**Comment by skolima** [comment]
Right, but `dotnet outdated` works only for dotnet core projects. That's a key limitation - and it still has to limits the depth of traversal (even with a `project.json` parsing approach) because it can be potentially too expensive. We'd also need NuKeeper to understand framework limitations (which `dotnet outdated` takes from the `project.json`) in order to resolve implicit resolutions. This is... complicated. Although it would come with benefits for other features as well.
