### ISSUE TITLE
Read Directory.Build.targets?

### ISSUE THREAD

**Issue by awelburn** [NuKeeperDotNet/NuKeeper#478]
I'm using the approach detailed in this blog post : https://www.strathweb.com/2018/07/solution-wide-nuget-package-version-handling-with-msbuild-15/

I have a Directory.Build.targets file at the root of my repo that contains PackageReferences with a Version attribute set: `<PackageReference Update="Foo" Version="1.0.0" />`

I then have sub-directories that contain solutions with projects etc, inside each of the .csproj files I have PackageReferences without the Version attribute set:  `<PackageReference Include="Foo" />`

This allows the update of a PackageReference in the root file and the change is then inherited in all csproj files that have the reference.

I've read the documentation, but I can't seem to figure out how to call NuKeeper to have it read this file instead of the individual csproj files. Am I doing something wrong?

**Comment by skolima** [comment]
That's not supported by NuKeeper currently. I think it's not supported by the package management UI in VS either, so far?

Currently NuKeeper does not do a full MSBuild parsing of the build scripts, so things that go too far away from the convention, while being still valid build scripts, are not be handled by NuKeeper.

#466  and #311 are related.

There might be a workaround possible to implement for `.targets` files - if `dotnet` is able to update those, then we could treat them as just another extension for project file, along `.csproj`.

**Comment by skolima** [comment]
Managing those references isn't supported by `dotnet` either, I'm afraid. As NuKeeper relies on the platform tooling to performs its operations, I don't think there's anything we can do here.

```
C:\test>dotnet add project.csproj package -v 7.0.1 AutoMapper
  Writing C:\Users\skolima\AppData\Local\Temp\tmp7783.tmp
info : Adding PackageReference for package 'AutoMapper' into project 'project.csproj'.
log  : Restoring packages for C:\test\project.csproj...
info : Package 'AutoMapper' is compatible with all the specified frameworks in project 'project.csproj'.
error: Cannot modify an evaluated object originating in an imported file "C:\test\Directory.Build.targets".
```

**Comment by awelburn** [comment]
Yes, there is no UI support for this setup.

My objective is probably simpler than imagined - just getting the inspect command to work would be a great help to me.

As you suggested I've forked and tried adding the .targets extension to ProjectFileReader, I also had to adjust the XmlToPackage method to use the Update attribute if the Include attribute is null etc.

I've added some unit tests that confirm this works. BTW - how can I test my forked copy of NuKeeper locally (outside of unit tests) with my real Directory.Build.targets?

Would the project like a PR for this limited support of Directory.Build.targets?

**Comment by AnthonySteele** [comment]
You can run nukeeper locally. Inside the global tool package it's just a commanline app. You can use `--` to force params after that to be passed to nukeeper not dotnet. e.g.
```
cd c:\code\NuKeeper\NuKeepr
dotnet run -- inspect --otherflags
```

**Comment by slang25** [comment]
I think reading the xmls as is done today isn't a great approach, it's a great first step, but I wouldn't extend that to make it understand Directory.Build.props for example. I think it's best to accept that you want to evaluate things the same way msbuild does, this leads to a few options, the best of which are (IMO):

- Using `Microsoft.Build`, I've tried this, but there's extra work required to set it up to know about the dotnet core sdk for example, this will be tricky.
- Using [Buildalyzer](https://github.com/daveaglick/Buildalyzer/) to get the project references, it basically solves the above problem for us.
- Using `dotnet msbuild /t:GenerateRestoreGraphFile /p:RestoreGraphOutputPath=graphoutput` via the command line and parsing that.

**Comment by AnthonySteele** [comment]
A few comments

- I won't look at this in a 0.9.x the next few weeks and next few versions, the output system is still being bedded down and also needs docs etc.

- NuKeeper itself has [packages in a Directory.Build.props file now](https://github.com/NuKeeperDotNet/NuKeeper/blob/master/Directory.Build.props#L18) for the code analysers. NuKeeper should be able to deal with it's own code. We start with simple cases and self-updates. However we also want a path that won't require more code and special handling for every quirk.

- What is the usual way for updating these shared package refs without NuKeeper? As far as I know, the VS and commandline tools don't work with them. Since NuKeeper shells out to `dotnet` for package updates, if this can't be done easily by `dotnet`, it's much harder. 

- It's worth looking into other libraries more, be it Nuget's types for version ranges ( #466) , or `Buildalyzer`. 

- What is the execution time? If it can cover more cases, in around the same run time, then that's a win! But `dotnet-outdated` is significantly slower than NuKeeper, because it does a build.

**Comment by slang25** [comment]
My understanding is that there are 2 contexts with regards to `PackageReference`s, there's the msbuild evaluation, which is very dynamic and complex, and will happen when you build or restore.

Then there's how tooling see's things which is more approximated. For example dotnet/msbuild restore, it only respects targetframework conditions, if you tried to restrict packages by platform or configuration then it just ignores it. If you do nuget restore then it ignores Directoy.Build.props, but dontnet/msbuild restore work fine. If you use conditions in Visual Studio for Mac then you have to wrap your package references in `Choose` elements, the whole thing is a mess tbh.

Given we want to then update the reference in the source (or delegate to a tool to do it), then something has to be done, and following your points, evaluating what packages are references doesn't solve the problem of updating them, so a static process is the way to go, I wasn't thinking when I made my previous suggestion.

The thing I had in my mind was the example of solution level versioning, in the example mentioned in this issue, you'd have to build the idea of include/update etc... where do you stop. If you want to do solution level versioning, arguably the more correct way is to use [Microsoft.Build.CentralPackageVersions](https://github.com/Microsoft/MSBuildSdks/tree/master/src/CentralPackageVersions). You'd need to build up these special cases, which is all do-able. In my mind a better stance is saying that it's a problem for the nuget client to solve. On the flip side, it becomes a unique selling point for NuKeeper!

**Comment by AnthonySteele** [comment]
Updating simple `directory.build.props` files like the one that NuKeeper itself uses, is very much doable using [code along the lines as this](https://github.com/NuKeeperDotNet/NuKeeper/pull/264).

But it's a hard problem in the general case, because the direction build props file can contain `<Import Project="anyotherfile.props" />` - [here's the docs](https://docs.microsoft.com/en-us/visualstudio/msbuild/import-element-msbuild?view=vs-2017). I have usually seen that used for a separate `version props` file but it's more flexible than that. I would expect it to be recursive too.
