### ISSUE TITLE
Ability to hook in commands

### ISSUE THREAD

**Issue by alexanderwilliamson** [NuKeeperDotNet/NuKeeper#568]
Hey, loving the good work. I'm looking to try and get this running with our workflow.

Right now each repository contains a file which denotes the semver. It looks something like this.
```
major: 1
minor: 2
patch: 0
(etc)
```
Each time we create a PR we have the ability to update this file. Most of the time it's always updated, but if you're making a minor change, or working together there's no reason to update the semver. There is a ruby gem we run along the lines of `semver inc minor` which increments the versioning.

## Requirement

When NuKeeper runs, I'd like a way to be able to run a command (like updating that file in the repo) before pushing the files up to a new PR.

## Proposal 1 - The quick-n-dirty workaround - Execute custom script before PR creation

All I can see for now is running `nukeeper repo (etc)` but this command does not let me call out to change this file, or hook in another command. Does anyone have suggestions for this? To move me along I could put a prebuild task in to increment the build then as the `nukeeper repo` command runs it could call out to a .bat or .pr1 or whatever. I understand you are trying to keep this cross platform.

Changes here:
- Ability to hook into and run random file after git pull, and before git PR creation

## Proposal 2 - Update `nukeeper update` and create new command to push

Another approach I could think of would be to have a `nukeeper update` command do the update in the local file system, then I update the semver (through whatever means), then have a new command similar to `nukeeper push`. This would need a few changes. Right now the PR comment cannot be extracted, and is different from the `-o` output file from the `nukeeper update` command. It would be awesome if that could be output to a file by command line.

- `nukeeper update` would ideally create a .md file of the changes
- the ability to step out of the NuKeeper lifecycle and hook something in here (.bat, .ps1, .sh, etc.)
- A new command like `nukeeper push` to do the work the push part of `nukeeper repo` command does, taking in the `.md` file for changes

I hope that makes sense!

**Comment by AnthonySteele** [comment]
Proposal one is very possible, Running commands is something that NuKeeper has done right from the start -  it shells out to `dotnet` and/or `nuget.exe`. Getting a good design is important though. I have 2 suggestions here:

* **Convention** NuKeeper could locate files in the root of the repo that match a certain spec and execute them just before making the PR.  e.g. `NuKeeperBeforePullrequest.(bat|ps1|sh)`. The problem is, what if you have one for linux and one for windows? It's hard to tell which should be run. it's not simple, there is powershell on linux and bash on windows. 

* **Configuration** A commandline option e.g. `--BeforePullRequestScript .\BeforePs.ps1` to specify a path to a script (relative to the repo root). This puts more complexity on the commandline, and it's up to you to be sure that your script can run (e.g. if it needs ruby then the machines should have ruby). 

In both cases, would the script be given data from nukeeper as args?

**Comment by 3686** [comment]
Thanks for getting back to me.

I think I'd prefer configuration over convention here, I prefer your second proposal (but still happy for either). 

I wondered if passing in another `dotnet tool` command plus arguments? Would that be more compatible? It sounds unnecessary. If the file is in my local folder, then I can write whatever I want into it and just use it as a hook, so no preference.

Agree with your point it's up to me to make sure the  call will run (Ruby etc.).

In my case I need to manipulate files in the PR before it is sent up, so I'd also need access to the files. So nukeeper would run the first half of the process, call my hook, let me modify the file, then send nukeeper changes + my changes in the PR. Happy for it to be a second commit on the PR for clairty.

I think that will be today's workaround, grepping the output and working out where the PR is the using git commands to update the file and push a second commit, downside is two CI builds.

RE passing data to process - Personal preference would be to dump out variables into a file (optionally, flaggable) so I can get more information about the nukeeper state, but wouldn't need this at this point in time.
