### ISSUE TITLE
Updates only if at least minor version changes

### ISSUE THREAD

**Issue by lukaskolafa** [NuKeeperDotNet/NuKeeper#932]
## 🚀 Feature Requests

It is possible to restrict updates when major version changes, this is very useful. I believe it would be as well cool having a restriction from bottom - update only if there is a change at least in minor version. This would avoid too much spam when you have lot of packages and the changes are only in the build number having same minor and major version.

### Contextualize the feature

Such restriction would make sense if you want to update automatically only in case there are some significant changes - avoiding spam.

### Describe the feature

New parameter that would ignore package updates in case there is no change on defined level (eg. minor version). 

### Platforms affected (mark all that apply)
- [ ] :hammer_and_wrench: NuKeeper CLI
- [ ] :sparkles: GitHub
- [x] :robot: AzureDevops
- [ ] :checkered_flag: Bitbucket
- [ ] :earth_americas: Gitlab
- [ ] :tv: Gitea
- [ ] :whale: Docker

**Comment by CrispyDrone** [comment]
If you are worried about getting too many pull requests in your repositories, I have a pull request open to allow specifying a limit on the number of pull requests that can be open at a time, you can check it out [here](https://github.com/NuKeeperDotNet/NuKeeper/pull/1043).

I personally think that saying "I only want a minor update" is counter productive because semantic versioning allows us to take advantage of patch updates that give us bug fixes (that can include important security fixes too!). You should be applying bug fixes as soon as possible. To deal with spam, I think the solution of having a limit on the number of open pull requests is a more appropriate solution.
